version: '3.4'

services:
  db:
    image: rest-with-aspnet-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_aspnet
    ports:
      - 3308:3306
    networks:
      - my-network
      
  rest-with-aspnet:
    image: rest-with-aspnet
    build:
      context: .
      dockerfile: RestWithAspNet/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
